spring:
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
  datasource:
    url: jdbc:postgresql://localhost:5432/permitdb
    username: ${PERMIT_DB_USER}
    password: ${PERMIT_DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: permit-api

server:
  port: 8080
  max-http-request-header-size: 8KB

app:
  test: hello-world

management:
  endpoint:
    health:
      show-details: never  # hide component-level health info
  endpoints:
    web:
      exposure:
        include: health, info
