spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/permitdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: permit-api

server:
  port: 8080

app:
  test: hello-world

management:
  endpoint:
    health:
      show-details: never  # hide component-level health info
  endpoints:
    web:
      exposure:
        include: health, info
